name = "Test Cateogry TOML"
time_sensitive = true
description = "a test cat using toml"

[[tasks]]
name = "task1"
desc = "desc for task1"
time = 1

[[tasks]]
name = "task2"
desc = "desc for task2"
time = 1

[[tasks]]
name = "task3"
desc = "desc for task3"
time = 1

[[tasks]]
name = "task4"
desc = "desc for task4"
time = 2

[[tasks]]
name = "task5"
desc = "desc for task5"
time = 2

[[tasks]]
name = "task6"
desc = "desc for task6"
time = 2

[[tasks]]
name = "task7"
desc = "desc for task7"
time = 3

[[tasks]]
name = "task8"
desc = "desc for task8"
time = 3

[[tasks]]
name = "task9"
desc = "desc for task9"
time = 3