name = "Test Cateogry TOML"
time_sensitive = true
description = "a test cat using toml"

[[tasks]]
name = "task1"
desc = "desc for task1"
minutes =1

[[tasks]]
name = "task2"
desc = "desc for task2"
minutes =1

[[tasks]]
name = "task3"
desc = "desc for task3"
minutes =1

[[tasks]]
name = "task4"
desc = "desc for task4"
minutes =2

[[tasks]]
name = "task5"
desc = "desc for task5"
minutes =2

[[tasks]]
name = "task6"
desc = "desc for task6"
minutes =2

[[tasks]]
name = "task7"
desc = "desc for task7"
minutes =3

[[tasks]]
name = "task8"
desc = "desc for task8"
minutes =3

[[tasks]]
name = "task9"
desc = "desc for task9"
minutes =3